{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zxo.finder",
    "module": "finder-plugin",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yjyhka6jjffhxi6gljpx5mrqau"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "finder-plugin-0.3.jar",
          "url": "finder-plugin-0.3.jar",
          "size": 18908,
          "sha512": "dd1bd6b6c131248fb6104ed2cccfd9ca3e191b30cbe4afff4dcc36b2ade023ee986569d84b19cd36cf905129c63d11a1cf7cfbbc3c824ee2c4c8e4b7cc9974e0",
          "sha256": "8be1f8b087903b2b377d56bc3c87d22494dbe953bc699e6eec9f5354d9607b46",
          "sha1": "2c89bf192260cdb50295557e8e6c91665a1087ce",
          "md5": "c4b756d2e83ae5f2dff82a3d27361eb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "finder-plugin-0.3.jar",
          "url": "finder-plugin-0.3.jar",
          "size": 18908,
          "sha512": "dd1bd6b6c131248fb6104ed2cccfd9ca3e191b30cbe4afff4dcc36b2ade023ee986569d84b19cd36cf905129c63d11a1cf7cfbbc3c824ee2c4c8e4b7cc9974e0",
          "sha256": "8be1f8b087903b2b377d56bc3c87d22494dbe953bc699e6eec9f5354d9607b46",
          "sha1": "2c89bf192260cdb50295557e8e6c91665a1087ce",
          "md5": "c4b756d2e83ae5f2dff82a3d27361eb3"
        }
      ]
    }
  ]
}
