{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zxo.finder",
    "module": "finder-plugin",
    "version": "0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yib7d7hs4vbxji4buhskb5n3hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "finder-plugin-0.3.jar",
          "url": "finder-plugin-0.3.jar",
          "size": 16725,
          "sha512": "7e1d58919975f5c682935667acbfef1f56b7440276c44bbab53ecca3b1cff8437be4db02d089f628c833b26cd753ff0f963bd7a0ba1a43f1d15106434c787b2a",
          "sha256": "7ed837a67d2284a563f242acf140d43b0a749878f0c8ab448e47be3730d9eae1",
          "sha1": "c5821409c27b3492408bddcc6742cb4447a7c1b7",
          "md5": "07c612db10751ae903396dc5b194ebab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "finder-plugin-0.3.jar",
          "url": "finder-plugin-0.3.jar",
          "size": 16725,
          "sha512": "7e1d58919975f5c682935667acbfef1f56b7440276c44bbab53ecca3b1cff8437be4db02d089f628c833b26cd753ff0f963bd7a0ba1a43f1d15106434c787b2a",
          "sha256": "7ed837a67d2284a563f242acf140d43b0a749878f0c8ab448e47be3730d9eae1",
          "sha1": "c5821409c27b3492408bddcc6742cb4447a7c1b7",
          "md5": "07c612db10751ae903396dc5b194ebab"
        }
      ]
    }
  ]
}
