{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zxo.finder",
    "module": "finder-plugin",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6r6hxxmlnjbmdmdxul3ni3nrte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "finder-plugin-0.2.jar",
          "url": "finder-plugin-0.2.jar",
          "size": 12805,
          "sha512": "9ca9959b4189f2c5b46b09c9d2abe925ce8ec87347dbd822511ec85c2af782101850842f813de29da5b6de694e2c89e700ff0e8b954bb02f96ef8d01dd60ab54",
          "sha256": "80dcc2e78c5b8edfa2a0901e285d1d26c2a31e69fe9c211ecbfd550179ad996a",
          "sha1": "03e828f61af6a8c60de866d17bd3b9df4b915950",
          "md5": "996a956ca38338b9c8c9097e9b98a0bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "finder-plugin-0.2.jar",
          "url": "finder-plugin-0.2.jar",
          "size": 12805,
          "sha512": "9ca9959b4189f2c5b46b09c9d2abe925ce8ec87347dbd822511ec85c2af782101850842f813de29da5b6de694e2c89e700ff0e8b954bb02f96ef8d01dd60ab54",
          "sha256": "80dcc2e78c5b8edfa2a0901e285d1d26c2a31e69fe9c211ecbfd550179ad996a",
          "sha1": "03e828f61af6a8c60de866d17bd3b9df4b915950",
          "md5": "996a956ca38338b9c8c9097e9b98a0bd"
        }
      ]
    }
  ]
}
